Damasvin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/',include('menu.urls')),
    path('order/',include('order.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path

from menu.views import DrinkListView, CoffeeCreateView, BubbleteaCreateView, DrinkUpdateView, DrinkDeleteView

app_name = 'menu'

urlpatterns = [
    path('', DrinkListView.as_view(),name='list'),
    path('add_coffee/', CoffeeCreateView.as_view(),name='add_coffee'),
    path('add_bubbletea/', BubbleteaCreateView.as_view(),name='add_bubbletea'),
    path('update/<int:pk>/', DrinkUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/', DrinkDeleteView.as_view(),name='delete'),
]

menu/models.py
from django.db import models

class Drink(models.Model):
    category = models.CharField(max_length=20)
    name = models.CharField(max_length=20)
    price = models.PositiveIntegerField()
    image = models.ImageField(blank=True, upload_to="menu/%Y/%m/%d/")
    # image = models.ImageField(default='menu/no_image.png', upload_to="menu/%Y/%m/%d/") 기본 이미지

    def __str__(self):
        return f'카테고리: {self.category}, 이름: {self.name}, 가격: {self.price}'

class Coffee(Drink):
    pass

class Bubbletea(Drink):
    pass

order/models.py
from django.db import models

from menu.models import Drink


class Order(models.Model):
    # drink, stock, cup, ice, sugar, pearl, price
    drink = models.ForeignKey(Drink, on_delete=models.CASCADE, related_name='order')
    stock = models.PositiveIntegerField(default=1)
    cup = models.IntegerField()     #0: 레귤러, 1: 점보
    ice = models.IntegerField(default=100)  #0%, 50, 100, 150
    sugar = models.IntegerField(default=100)    #0%, 50, 100, 150
    price = models.IntegerField()

    def __str__(self):
        return f'음료 :{self.drink}, 개수 : {self.stock}, 컵 : {self.cup}, 얼음량 : {self.ice}, 당도 : {self.sugar}, 가격 : {self.price}'

menu/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from menu.models import Drink, Coffee, Bubbletea


class DrinkListView(ListView):
    model = Drink
    paginate_by = 3


class CoffeeCreateView(CreateView):
    model = Coffee
    fields = '__all__'      #['category','name','price','image']
    template_name = 'menu/drink_create.html'
    success_url = reverse_lazy('menu:list')  # DB에 저장된 후 늦게 호출해라.
    initial = {'category' : 'Coffee'}

class BubbleteaCreateView(CreateView):
    model = Bubbletea
    fields = '__all__'      #['category','name','price','image']
    template_name = 'menu/drink_create.html'
    success_url = reverse_lazy('menu:list')  # DB에 저장된 후 늦게 호출해라.
    initial = {'category' : 'Bubbletea'}


class DrinkUpdateView(UpdateView):
    model = Drink
    fields = '__all__'
    template_name_suffix = '_update'  # drink_update.html
    success_url = reverse_lazy('menu:list')


class DrinkDeleteView(DeleteView):
    model = Drink
    success_url = reverse_lazy('menu:list')

order/views.py
from django.shortcuts import render
from django.views.generic import ListView

from order.models import Order


class OrderListView(ListView):
    model = Order

menu/templates/menu/coffee_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Coffee Add</title>
</head>
<body>

</body>
</html>

menu/templates/menu/drink_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Drink Confirm Delete</title>
</head>
<body>
    <h1>{{ drink }}</h1>
    {% if drink.image != '' %}
    <img src="{{ drink.image.url }}" alt="" style="height: 200px">
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
        <button type="button" onclick="history.back()">Cancle</button>
    </form>
</body>
</html>

menu/templates/menu/drink_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Drink Add</title>
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add</button>
    <button type="button" onclick="history.back()">Cancel</button>
</form>
</body>
</html>

menu/templates/menu/drink_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Drink List</title>
</head>
<body>
<table>
    <thead>
    <tr>
        <th>#</th>
        <th>image</th>
        <th>Drink</th>
        <th>Modify</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for drink in drink_list %}
    <tr>
        <td>{{ forloop.counter }}</td>
        {% if drink.image != '' %}
        <td><img src="{{ drink.image.url }}" alt="아메리카노" width=100px"></td>
        {% else %}
            <td>----</td>
        {% endif %}
        <td>{{ drink }}</td>
        <td><a href="{% url 'menu:update' pk=drink.id %}">Modify</a></td>
        <td><a href="{% url 'menu:delete' pk=drink.id %}">Delete</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<a href="{% url 'menu:add_coffee' %}">Add Coffee</a>
<a href="{% url 'menu:add_bubbletea' %}">Add Bubbletea</a>
</body>
</html>

menu/templates/menu/drink_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Drink Update</title>
</head>
<body>

</body>
</html>

order/templates/order/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order List</title>
</head>
<body>
<table>
    <thead>
    <tr>
        <th>#</th>
        <th>order</th>
        <th>Modify</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for order in order_list %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ order }}</td>
        <td>Modify</td>
        <td>Delete</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>